### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by rybolia** [CampbellSoftwareSolutions/docker-osticket#33]
Hi there,

Instead of linking the containers through CLI I am trying to link them in docker-compose but I'm having trouble setting it up. 
[docker-compose.txt](https://github.com/CampbellSoftwareSolutions/docker-osticket/files/1556705/docker-compose.txt)

**Comment by idadzie** [comment]
This should help with the setup. :smile: 
```yml
version: '2'
services:
  osticket_mysql:
    image: mysql
    container_name: osticket_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: osticket
      MYSQL_PASSWORD: secretpassword
      MYSQL_USER: osticket
    ports:
      - "3333:3306"
  osticket:
    image: campbellsoftwaresolutions/osticket
    container_name: osticket
    links:
      - osticket_mysql:mysql
    environment:
      MYSQL_PORT: 3333
      MYSQL_DATABASE: osticket
      MYSQL_PASSWORD: secretpassword
      MYSQL_USER: osticket
    ports:
      - "8888:80"  
    extra_hosts:
      - "ldap:x.x.x.x"
```
__NOTE: x.x.x.x refers to an I.P. address eg. 192.168.20.18__
