### ISSUE TITLE
i need a composefile for osticket and its database 

### ISSUE THREAD

**Issue by mobehairy** [CampbellSoftwareSolutions/docker-osticket#58]

**Comment by PromoFaux** [comment]
Here is what I am using, obviously replace out `secret` with your own secure passwords/secrets!

```yml
version: '3.4'
services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_PASSWORD: secret
      MYSQL_USER: osticket
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - 3306:3306

  osticket:
    container_name: osticket
    restart: unless-stopped
    image: campbellsoftwaresolutions/osticket
    depends_on:
      - mysql
    environment:
      INSTALL_SECRET: secret
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: secret
      CRON_INTERVAL: 1
    image: campbellsoftwaresolutions/osticket
    ports:
    - 8080:80
```
